---
gateway : "192.168.1.1"
dns: "192.168.1.148"

vms_to_create:
 - name: "client"
   ip_address: "192.168.1.104/24"
   memory: "1024"

 - name: "serv"
   ip_address: "192.168.1.105/24"
   memory: "1024"


